### ISSUE TITLE
Async option support

### ISSUE THREAD

**Issue by andrerpena** [najaxjs/najax#16]
`$.ajax` suports an option called `async` that does what the name suggests. It seems that `najax` doesn't support it. Right?

**Comment by doublerebel** [comment]
@andrerpena The [jQuery,ajax setting `async`](http://api.jquery.com/jquery.ajax/#jQuery-ajax-settings) defaults to `true`, which is najax's behavior.  All http requests in Node are asynchronous, so a synchronous http call would require dependency on a native-compiled module.  I believe that is out of the scope of najax.

**Comment by alanclarke** [comment]
@doublerebel some nodejs modules support sync calls, e.g. fs.readFileSync. This can be implemented using a while loop, and though it's not performant and hogs CPU the whole time and kind of is against the whole non-blocking ethos of node, there are convenience use cases for sync, such as tests or initial setup code
