### ISSUE TITLE
Won't post nested objects

### ISSUE THREAD

**Issue by hilltopmediadesign** [najaxjs/najax#17]
Excellent plugin. Had an issue with POST.  Would not pass a nested 'data' object when using "application/x-www-form-urlencoded".

Example:
var d = {   

  action: 'ajaxNode',  
  type: 'post',
  request: 'get_posts_by_user',
  data:{ID:'1',post_type:'notes'},
  
};   
 
najax({
    url: ajaxURL,
    type: 'POST',
    data: d 
},function(res){
  console.log(res);
});

d.data wouldn't get posted. Only a string will post.

I swapped module 'querystring' with 'qs' and removed line 97:
o.data = o.data+'\n';

Fixed the issue.

**Comment by doublerebel** [comment]
Hi @luminaia , I think this issue is fixed in master.  Is it the older najax from npm that caused the issue?

**Comment by luminaia** [comment]
This was from the npm version. Will test with git master and report back.

**Comment by luminaia** [comment]
Just tested -- same problem with the master.

**Comment by alanclarke** [comment]
heya @luminaia could you add a pr with a test case? happy to merge, and thanks for raising this

**Comment by alanclarke** [comment]
Hmm yeah, it seems node's native querystring module doesn't support nested params. I wonder what we should do here. I suppose it should behave like jquery does, I wonder if we can steal its parser/serialiser or something

**Comment by doublerebel** [comment]
**qs** is what [**express/bodyparser** uses in `extended` mode](https://github.com/expressjs/body-parser#extended).  I would support an extended mode for **najax** that uses **qs**.  The extended mode switch would avoid breaking any current code.

**Comment by alanclarke** [comment]
![content-type: json](http://i.imgur.com/PEuTRA8.png)

**Comment by alanclarke** [comment]
https://github.com/najaxjs/najax/pull/40
