### ISSUE TITLE
npm version outdated

### ISSUE THREAD

**Issue by doublerebel** [najaxjs/najax#3]
Hello,

Thanks for this lib!  Would you mind updating the npm package with the latest updates from Github?

Cheers,

Charles

**Comment by doublerebel** [comment]
Hey @alanclarke, no worries.  I ended up rather busy myself.  I'm starting open-source Fridays to keep up, and I'd be happy to help maintain this project permanently.

Hope you're having a great 2015!

**Comment by alanclarke** [comment]
Cool! You should have full access to the repo now, best wishes for the new year to you too :+1:

**Comment by doublerebel** [comment]
@alanclarke I've updated the dependencies and rewritten the tests in Mocha for test coverage with Blanket and Nock mocking.  I'd like to add this project to Travis-CI and Coveralls, but it looks like I only have collaborator access to this repo.  Could I have admin access, or would you be willing to add it to Travis and/or Coveralls?

**Comment by alanclarke** [comment]
Hey @doublerebel, I couldn't find any administrator role in the ui - as a collaborator I think you should have 'full access to the repository'?

**Comment by alanclarke** [comment]
btw sounds awesome!

**Comment by kataev** [comment]
Go Go! Npm version unusable with deffered.reject and json parse error!

**Comment by doublerebel** [comment]
@alanclarke My mistake, looks like we'd have to move this to an organization [to allow multiple admins](https://help.github.com/articles/what-are-the-different-access-permissions/).  I just created organization opensourcefridays, or we could move it to najax/najax ?

**Comment by alanclarke** [comment]
hey @doublerebel, you will receive an invite to the 'najax admins' team, which will make you an admin of this repo!

**Comment by alanclarke** [comment]
(unfortunately there is already a user called najax)

**Comment by seth-admittedly** [comment]
Is there an ETA on getting master pushed to npm? We need the fix for headers that's currently lagging the npm version.

**Comment by NickStefan** [comment]
bump

**Comment by alanclarke** [comment]
@doublerebel i added you as an owner on npm, soz for the delay!

**Comment by alanclarke** [comment]
also I published the latest version
