### ISSUE TITLE
Error when uploading PDF/binary file

### ISSUE THREAD

**Issue by helmuttheis** [najaxjs/najax#37]
I use your great plugin to upload PDF files to a server. Internally the data seems to be transformed to UTF-8. I have found 2 places where you add utf-8. At first when building the request header near line 68.
The second place is when the data is actually written, near line 207.
I have changed these as follows:

```
} else {
        /* set data content type */
        if (o.contentType === 'application/pdf') {
            o.headers = _.extend({
                'Content-Type': o.contentType,
                'Content-Length': o.data.length
            }, o.headers)

        }
        else {
            o.headers = _.extend({
                'Content-Type': o.contentType + ';charset=utf-8',
                'Content-Length': Buffer.byteLength(o.data)
            }, o.headers)

        }
```

and 
    // SEND DATA
    if (o.method !== 'GET' && o.data) {
        if (o.contentType === 'application/pdf') {
            req.write(o.data, 'binary');
        }
        else {
            req.write(o.data, 'utf-8');
        }
    }

This is a quick solution for PDF only. There should be a solution to handle all binary data, maybe an additional option or a list of all known minetypes.

**Comment by alanclarke** [comment]
Yeah, najax probably shouldn't assume utf8 to be fair, will add a pr when i get a min

**Comment by alanclarke** [comment]
https://github.com/najaxjs/najax/pull/55
