### ISSUE TITLE
Use native promises

### ISSUE THREAD

**Issue by alanclarke** [najaxjs/najax#39]
jQuery 3.0.0 release uses A+ spec promises, which have been native in nodejs land for some time

@doublerebel what do you think about getting rid of $.deferred dependency and perhaps even lodash tbh

**Comment by avindra** [comment]
I would love to see this. `$.ajax` is a very familiar API for web developers, and it should support the A+ spec for promises, to align with the future.

It should allow usage like this:

```js
import ajax from 'najax';

ajax({
   url : 'http://www.google.com/',
   data : {
       s : 'Latest proposals for esnext'
   }
}).then(response => console.log(response))
```

**Comment by avindra** [comment]
I support dropping lodash-- or instead, using a build system (and shipping it to `dist` on npm) is an option.

najax can use webpack, which will also allow the use of `es2015` to transform the whole code base into ES6 modules.  More importantly, there is a babel transform available for [optimizing lodash imports](https://www.npmjs.com/package/babel-plugin-lodash), which is really cool.

I'd totally be on board to help with an ES6 rewrite including the lodash plugin if anyone is interested :+1:

**Comment by alanclarke** [comment]
Thanks @avindra but I think babel, webpack and a build system are a bit overkill here, its such a simple module and the native api is more than sufficient

However, I'd be up for dropping support for node < 4.4.3 and using the native es6 features that are available there. We'd have to bump the major version and be consistent with jquery 3.0.0's api
