### ISSUE TITLE
lodash dep is 4.6M

### ISSUE THREAD

**Issue by pwfisher** [najaxjs/najax#43]
```
4.6M    /app/server/node_modules/najax/node_modules/lodash
```

Does najax really need to include all of lodash? Can we just include the parts we need? This is very heavy for "nano" ajax.

**Comment by alanclarke** [comment]
Yeah we can totally get rid of lodash: https://github.com/najaxjs/najax/pull/44

Strange that it's so huge! Their full build is advertised as just 22kb

**Comment by alanclarke** [comment]
merged!
