### ISSUE TITLE
charset=utf-8 set on every non GET request

### ISSUE THREAD

**Issue by juanazam** [najaxjs/najax#49]
Hi,

I'm using https://github.com/ember-fastboot/ember-cli-fastboot, which uses `najax` to work and I have an API server that handles JSON API requests. The thing is that `najax` is sending the `charset` parameter on the `Content-type` header of every non GET request.

The JSON API spec doesn't allow any parameters on that header explicitly: http://jsonapi.org/format/#content-negotiation-servers.

Looking at the code, the parameter is added to header regardless of the content type itself which doesn't seem to be correct: https://github.com/najaxjs/najax/blob/master/lib/najax.js#L69.

**Comment by alanclarke** [comment]
@juanazam thanks for bringing this up, we would welcome a pr?

**Comment by alanclarke** [comment]
@juanazam does https://github.com/najaxjs/najax/pull/55 resolve your issue?

**Comment by juanazam** [comment]
@alanclarke it does! thanks!
