### ISSUE TITLE
Headers persist through multiple requests

### ISSUE THREAD

**Issue by DrewCarlson** [najaxjs/najax#50]
The `headers` passed in via `options` is improperly being merged into `defaults` causing headers from a previous request to be reused.

See https://github.com/DrewCarlson/najax/tree/header-disposal for a failing test.

**Comment by alanclarke** [comment]
https://github.com/najaxjs/najax/pull/54

**Comment by Turbo87** [comment]
@alanclarke this is unfortunately still broken in v1.0.0
